echo ""
echo "                                                     ####"
echo "                                                    #    #"
echo "                                                   #      #"
echo "                                                    #    #"
echo " ####   #####    #####    # ##   ####     ####  #    ####"
echo "     #  #    #   #    #   ##    #    #   #          #    #"
echo " #####  #     #  #     #  #     ######  #       #  #      #"
echo "#    #  #    #   #    #   #     #        #      #   #    #"
echo " #####  #####    #####    #      ####     ####  #    ####"
echo "        #        #"
echo "        #        #"
echo "        #        #"
echo ""
echo "(c) Sarah Sandmann"
date
echo ""
